[package]
name = "bevy_panorbit_camera"
version = "0.5.0"
authors = ["Plonq"]
edition = "2021"
description = "A basic pan and orbit camera in Bevy"
keywords = ["gamedev", "bevy", "orbit", "camera"]
categories = ["game-development"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Plonq/bevy_panorbit_camera"
homepage = "https://github.com/Plonq/bevy_panorbit_camera"
readme = "README.md"

[features]
default = [ "bevy_egui", "bevy-inspector-egui" ]
bevy_egui = ["dep:bevy_egui"]
bevy-inspector-egui = ["dep:bevy-inspector-egui"]

[dependencies]
bevy = { version = "0.10", default-features = false }
bevy_easings = "0.10"
bevy_egui = { version = "0.20", optional = true, default-features = false }
bevy-inspector-egui = { version = "0.18.3", optional = true, default-features = false }

[dev-dependencies]
bevy = { version = "0.10" }
bevy-inspector-egui = { version = "0.18.3", default-features = false }
float-cmp = "0.9.0"

[[example]]
name = "egui"
required-features = ["bevy_egui"]
